---
- hosts: all 
  remote_user: vagrant
  become: yes
  roles:
    - docker-installation
    - kubernetes-common-utils

- hosts: kmaster 
  remote_user: vagrant
  become: yes
  roles:
    - kubernete-master-installation

- hosts: workers 
  remote_user: vagrant
  become: yes
  roles:
    - kubernete-nodes
